

from typing import Text
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 643)
        MainWindow.setStyleSheet("background-color: rgb(243, 255, 255);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.cButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('C'))
        self.cButton.setGeometry(QtCore.QRect(10, 150, 121, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.cButton.setFont(font)
        self.cButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.cButton.setAutoDefault(False)
        self.cButton.setObjectName("cButton")
        self.delButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.del_button())
        self.delButton.setGeometry(QtCore.QRect(150, 150, 111, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.delButton.setFont(font)
        self.delButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.delButton.setAutoDefault(False)
        self.delButton.setObjectName("delButton")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('%'))
        self.percentButton.setGeometry(QtCore.QRect(190, 510, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.percentButton.setFont(font)
        self.percentButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.percentButton.setAutoDefault(False)
        self.percentButton.setObjectName("percentButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('/'))
        self.divideButton.setGeometry(QtCore.QRect(280, 150, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.divideButton.setFont(font)
        self.divideButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.divideButton.setAutoDefault(False)
        self.divideButton.setObjectName("divideButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('8'))
        self.eightButton.setGeometry(QtCore.QRect(100, 240, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.eightButton.setFont(font)
        self.eightButton.setAutoDefault(False)
        self.eightButton.setObjectName("eightButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('9'))
        self.nineButton.setGeometry(QtCore.QRect(190, 240, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.nineButton.setFont(font)
        self.nineButton.setAutoDefault(False)
        self.nineButton.setObjectName("nineButton")
        self.mulButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('*'))
        self.mulButton.setGeometry(QtCore.QRect(280, 240, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.mulButton.setFont(font)
        self.mulButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.mulButton.setAutoDefault(False)
        self.mulButton.setObjectName("mulButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('7'))
        self.sevenButton.setGeometry(QtCore.QRect(10, 240, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sevenButton.setFont(font)
        self.sevenButton.setAutoDefault(False)
        self.sevenButton.setObjectName("sevenButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('5'))
        self.fiveButton.setGeometry(QtCore.QRect(100, 330, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fiveButton.setFont(font)
        self.fiveButton.setAutoDefault(False)
        self.fiveButton.setObjectName("fiveButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('6'))
        self.sixButton.setGeometry(QtCore.QRect(190, 330, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sixButton.setFont(font)
        self.sixButton.setAutoDefault(False)
        self.sixButton.setObjectName("sixButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('-'))
        self.minusButton.setGeometry(QtCore.QRect(280, 330, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.minusButton.setFont(font)
        self.minusButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.minusButton.setAutoDefault(False)
        self.minusButton.setObjectName("minusButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('4'))
        self.fourButton.setGeometry(QtCore.QRect(10, 330, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.fourButton.setFont(font)
        self.fourButton.setAutoDefault(False)
        self.fourButton.setObjectName("fourButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('2'))
        self.twoButton.setGeometry(QtCore.QRect(100, 420, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.twoButton.setFont(font)
        self.twoButton.setAutoDefault(False)
        self.twoButton.setObjectName("twoButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('3'))
        self.threeButton.setGeometry(QtCore.QRect(190, 420, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.threeButton.setFont(font)
        self.threeButton.setAutoDefault(False)
        self.threeButton.setObjectName("threeButton")
        self.plusButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('+'))
        self.plusButton.setGeometry(QtCore.QRect(280, 420, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.plusButton.setFont(font)
        self.plusButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.plusButton.setAutoDefault(False)
        self.plusButton.setObjectName("plusButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('1'))
        self.oneButton.setGeometry(QtCore.QRect(10, 420, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.oneButton.setFont(font)
        self.oneButton.setAutoDefault(False)
        self.oneButton.setObjectName("oneButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_button('0'))
        self.zeroButton.setGeometry(QtCore.QRect(10, 510, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.zeroButton.setFont(font)
        self.zeroButton.setAutoDefault(False)
        self.zeroButton.setObjectName("zeroButton")
        self.dotButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.dot_button())
        self.dotButton.setGeometry(QtCore.QRect(100, 510, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.dotButton.setFont(font)
        self.dotButton.setAutoDefault(False)
        self.dotButton.setObjectName("dotButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.equal_button())
        self.equalButton.setGeometry(QtCore.QRect(280, 510, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.equalButton.setFont(font)
        self.equalButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.equalButton.setAutoDefault(False)
        self.equalButton.setObjectName("equalButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def press_button(self, pressed):
            if pressed == 'C':
                self.label.setText('0')
                self.label_2.setText('')
            else:
                if self.label.text() == '0':
                    self.label.setText('')
                self.label.setText(f'{self.label.text()}{pressed}')

    def equal_button(self):
        screen = self.label.text()
        try:
            answer = eval(screen)
            self.label.setText(str(answer))
        except:
            self.label.setText('ERROR')

    def del_button(self):
        screen = self.label.text()
        screen = screen[:-1]
        self.label.setText(screen)

    def dot_button(self):
        screen = self.label.text()
        if '.' in screen:
            pass
            if '+' in screen:
                self.label.setText(f'{screen}.')
        else:
            self.label.setText(f'{screen}.')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.label.setText(_translate("MainWindow", "0"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.delButton.setText(_translate("MainWindow", "Del"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.mulButton.setText(_translate("MainWindow", "*"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.dotButton.setText(_translate("MainWindow", "."))
        self.equalButton.setText(_translate("MainWindow", "="))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
